language: python
sudo: false

python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8-dev"

matrix:
  allow_failures:
      - python: "3.8-dev"

virtualenv:
  system_site_packages: false

services:
  - postgresql

addons:
  postgresql: "9.6"

install:
  - pip install flake8
  - pip install coverage
  - pip install nose
  - pip install coveralls
  - pip install -e .

env:
  global:
    - ANYBLOK_DATABASE_NAME=travis_ci_test
    - ANYBLOK_DATABASE_DRIVER=postgresql
    - ANYBLOK_DATABASE_USER=postgres

script:
  - flake8 anyblok_wms_base
  - python3 run_all_tests.py -- -v

after_success:
  coveralls
